# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-22 00:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20161221_2151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ctacte',
            options={'verbose_name': 'Cuenta Corriente', 'verbose_name_plural': 'Cuentas Corrientes'},
        ),
    ]
