# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 04:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20161230_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationByUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False, verbose_name='Notificaci\xf3n vista')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('notification', models.TextField(verbose_name='Notificaci\xf3n')),
                ('active', models.BooleanField(default=True, verbose_name='Activa/Inactiva')),
            ],
        ),
        migrations.AddField(
            model_name='notificationbyuser',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Notifications'),
        ),
        migrations.AddField(
            model_name='notificationbyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
