# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-16 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170116_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationbyuser',
            options={'verbose_name': 'Notificaci\xf3n por Usuario', 'verbose_name_plural': 'Notificaciones por Usuario'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'Notificaci\xf3n', 'verbose_name_plural': 'Notificaciones'},
        ),
    ]
