# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-18 04:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170116_0202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationByUser',
            new_name='ViewedNotifications',
        ),
    ]
