# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170118_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='address_street',
            field=models.CharField(max_length=150, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='exporter_name',
            field=models.CharField(max_length=150, verbose_name='Nombre Exportador'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='exporter_name_group1',
            field=models.CharField(max_length=150, verbose_name='Nombre Exportador Grupo1'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='exporter_name_group2',
            field=models.CharField(max_length=150, verbose_name='Nombre Exportador Grupo2'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Raz\xf3n Social'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='tax_address_street',
            field=models.CharField(max_length=150, verbose_name='Calle Dom. Fiscal'),
        ),
    ]
