# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170120_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='email',
            field=models.CharField(max_length=150, verbose_name='Email'),
        ),
    ]
