# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170120_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='email',
            field=models.CharField(max_length=300, verbose_name='Email'),
        ),
    ]
