# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20170120_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='tax_tel',
            field=models.CharField(max_length=80, verbose_name='Tel\xe9fono Fiscal'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='tel',
            field=models.CharField(max_length=80, verbose_name='Tel\xe9fono'),
        ),
    ]
