# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-20 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170120_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='address_floor',
            field=models.CharField(max_length=10, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='tax_address_floor',
            field=models.CharField(max_length=10, verbose_name='Piso Dom. Fiscal'),
        ),
    ]
