# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_ctactekilos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctactekilos',
            name='blank_5',
            field=models.IntegerField(verbose_name='Blanco 5'),
        ),
    ]
