# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-25 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20170124_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctactekilos',
            name='gross_kg',
            field=models.IntegerField(verbose_name='Peso Bruto'),
        ),
    ]
