# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-09 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_ctactekilos_speciesharvest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.IntegerField(verbose_name='Tipo de Entidad')),
                ('algoritmo_code', models.IntegerField(verbose_name='Cuenta Algoritmo')),
                ('name', models.CharField(max_length=150, verbose_name='Raz\xf3n Social')),
                ('address_street', models.CharField(max_length=150, verbose_name='Calle')),
                ('address_number', models.CharField(max_length=10, verbose_name='Numero')),
                ('address_floor', models.CharField(max_length=10, verbose_name='Piso')),
                ('address_apartment', models.CharField(max_length=10, verbose_name='Depto.')),
                ('postal_code', models.CharField(max_length=10, verbose_name='C\xf3digo Postal')),
                ('postal_sufix', models.CharField(max_length=10, verbose_name='Sufijo')),
                ('location', models.CharField(max_length=50, verbose_name='Localidad')),
                ('state', models.CharField(max_length=80, verbose_name='Provincia')),
                ('tel', models.CharField(max_length=80, verbose_name='Tel\xe9fono')),
                ('amount', models.FloatField(verbose_name='Importe del Comprobante')),
                ('movement_type', models.CharField(max_length=7, verbose_name='Tipo Movimiento')),
                ('account_balance', models.FloatField(verbose_name='Saldo Cuenta')),
                ('affected_voucher_balance', models.FloatField(verbose_name='Saldo de Movimientos Afectados')),
                ('voucher', models.CharField(max_length=16, verbose_name='Comprobante')),
                ('afected_voucher', models.CharField(max_length=16, verbose_name='Comprobante Afectado')),
                ('voucher_date', models.DateField(null=True, verbose_name='Fecha Comprobante')),
                ('afected_date', models.DateField(null=True, verbose_name='Fecha Afectado')),
                ('expiration_date', models.DateField(null=True, verbose_name='Fecha Vencimiento')),
                ('issue_date', models.DateField(null=True, verbose_name='Fecha Emision')),
                ('concept', models.CharField(max_length=200, verbose_name='Concepto')),
                ('cta_cte', models.CharField(max_length=1, verbose_name='Codigo de Cta. Cte.')),
                ('cta_cte_description', models.CharField(max_length=50, verbose_name='Descripcion de Cta. Cte.')),
                ('cta_cte_detail', models.CharField(max_length=100, verbose_name='Detalle de Cta. Cte.')),
                ('amount_usd', models.FloatField(verbose_name='Importe del Comprobante en USD')),
                ('modify_balance', models.CharField(max_length=2, verbose_name='Modifica Saldo')),
                ('account_balance_usd', models.FloatField(verbose_name='Saldo Cuenta en USD')),
                ('affected_balance_usd', models.FloatField(verbose_name='Saldo Afectado en USD')),
                ('link', models.CharField(max_length=100, verbose_name='Detalle de Cta. Cte.')),
                ('currency', models.CharField(max_length=1, verbose_name='Moneda')),
                ('cuit', models.CharField(max_length=13, verbose_name='CUIT')),
                ('cbu', models.CharField(max_length=27, verbose_name='CBU')),
                ('zone', models.IntegerField(verbose_name='Codigo de Zona')),
                ('zone_name', models.CharField(max_length=80, verbose_name='Descripcion Zona')),
                ('amount_sign', models.FloatField(verbose_name='Importe Signo')),
                ('numeric_voucher', models.CharField(max_length=12, verbose_name='Comprobante Numerico')),
                ('internal_contract', models.CharField(max_length=80, verbose_name='Contrato Interno')),
                ('export_contract', models.CharField(max_length=80, verbose_name='Contrato Exportador')),
                ('exporter', models.IntegerField(verbose_name='Exportador')),
                ('exporter_name', models.CharField(max_length=150, verbose_name='Nombre Exportador')),
                ('exporter_group1', models.IntegerField(verbose_name='Exportador Grupo1')),
                ('exporter_name_group1', models.CharField(max_length=150, verbose_name='Nombre Exportador Grupo1')),
                ('exporter_group2', models.IntegerField(verbose_name='Exportador Grupo2')),
                ('exporter_name_group2', models.CharField(max_length=150, verbose_name='Nombre Exportador Grupo2')),
                ('exchange_rate', models.FloatField(verbose_name='Tipo de Cambio Emisi\xf3n')),
                ('debit_amount_pes', models.FloatField(verbose_name='Saldo Debito $')),
                ('credit_amount_pes', models.FloatField(verbose_name='Saldo Credito $')),
                ('debit_amount_usd', models.FloatField(verbose_name='Saldo Debito USD')),
                ('credit_amount_usd', models.FloatField(verbose_name='Saldo Credito USD')),
            ],
        ),
    ]
