# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('dn', models.FloatField(verbose_name='Dolar Naci\xf3n')),
                ('dl', models.FloatField(verbose_name='Dolar Libre')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
        migrations.AlterModelOptions(
            name='applied',
            options={'verbose_name': 'Cuenta Corriente Aplicada', 'verbose_name_plural': 'Cuentas Corrientes Aplicadas'},
        ),
        migrations.AlterModelOptions(
            name='ctactekilos',
            options={'verbose_name': 'Cuenta Corriente en Kilos', 'verbose_name_plural': 'Cuentas Corrientes en Kilos'},
        ),
    ]
