# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20170211_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='dl',
            new_name='dl_buy',
        ),
        migrations.RenameField(
            model_name='currencies',
            old_name='dn',
            new_name='dn_buy',
        ),
        migrations.AddField(
            model_name='currencies',
            name='dl_sell',
            field=models.FloatField(default=0, verbose_name='Dolar Libre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currencies',
            name='dn_sell',
            field=models.FloatField(default=0, verbose_name='Dolar Naci\xf3n'),
            preserve_default=False,
        ),
    ]
