# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20170212_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('wheat_ros', models.FloatField(verbose_name='Trigo')),
                ('wheat_bas', models.FloatField(verbose_name='Trigo')),
                ('wheat_qq', models.FloatField(verbose_name='Trigo')),
                ('wheat_bb', models.FloatField(verbose_name='Trigo')),
                ('wheat12_ros', models.FloatField(verbose_name='Trigo Art. 12')),
                ('wheat12_bas', models.FloatField(verbose_name='Trigo Art. 12')),
                ('wheat12_qq', models.FloatField(verbose_name='Trigo Art. 12')),
                ('wheat12_bb', models.FloatField(verbose_name='Trigo Art. 12')),
                ('corn_ros', models.FloatField(verbose_name='Maiz')),
                ('corn_bas', models.FloatField(verbose_name='Maiz')),
                ('corn_qq', models.FloatField(verbose_name='Maiz')),
                ('corn_bb', models.FloatField(verbose_name='Maiz')),
                ('sunflower_ros', models.FloatField(verbose_name='Girasol')),
                ('sunflower_bas', models.FloatField(verbose_name='Girasol')),
                ('sunflower_qq', models.FloatField(verbose_name='Girasol')),
                ('sunflower_bb', models.FloatField(verbose_name='Girasol')),
                ('soy_ros', models.FloatField(verbose_name='Soja')),
                ('soy_bas', models.FloatField(verbose_name='Soja')),
                ('soy_qq', models.FloatField(verbose_name='Soja')),
                ('soy_bb', models.FloatField(verbose_name='Soja')),
                ('sorghum_ros', models.FloatField(verbose_name='Sorgo')),
                ('sorghum_bas', models.FloatField(verbose_name='Sorgo')),
                ('sorghum_qq', models.FloatField(verbose_name='Sorgo')),
                ('sorghum_bb', models.FloatField(verbose_name='Sorgo')),
            ],
            options={
                'verbose_name': 'Pizarra',
                'verbose_name_plural': 'Pizarras',
            },
        ),
    ]
