# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-13 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='corn_bas',
            field=models.FloatField(default=0, verbose_name='Maiz'),
        ),
        migrations.AlterField(
            model_name='board',
            name='corn_bb',
            field=models.FloatField(default=0, verbose_name='Maiz'),
        ),
        migrations.AlterField(
            model_name='board',
            name='corn_qq',
            field=models.FloatField(default=0, verbose_name='Maiz'),
        ),
        migrations.AlterField(
            model_name='board',
            name='corn_ros',
            field=models.FloatField(default=0, verbose_name='Maiz'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sorghum_bas',
            field=models.FloatField(default=0, verbose_name='Sorgo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sorghum_bb',
            field=models.FloatField(default=0, verbose_name='Sorgo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sorghum_qq',
            field=models.FloatField(default=0, verbose_name='Sorgo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sorghum_ros',
            field=models.FloatField(default=0, verbose_name='Sorgo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='soy_bas',
            field=models.FloatField(default=0, verbose_name='Soja'),
        ),
        migrations.AlterField(
            model_name='board',
            name='soy_bb',
            field=models.FloatField(default=0, verbose_name='Soja'),
        ),
        migrations.AlterField(
            model_name='board',
            name='soy_qq',
            field=models.FloatField(default=0, verbose_name='Soja'),
        ),
        migrations.AlterField(
            model_name='board',
            name='soy_ros',
            field=models.FloatField(default=0, verbose_name='Soja'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sunflower_bas',
            field=models.FloatField(default=0, verbose_name='Girasol'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sunflower_bb',
            field=models.FloatField(default=0, verbose_name='Girasol'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sunflower_qq',
            field=models.FloatField(default=0, verbose_name='Girasol'),
        ),
        migrations.AlterField(
            model_name='board',
            name='sunflower_ros',
            field=models.FloatField(default=0, verbose_name='Girasol'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat12_bas',
            field=models.FloatField(default=0, verbose_name='Trigo Art. 12'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat12_bb',
            field=models.FloatField(default=0, verbose_name='Trigo Art. 12'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat12_qq',
            field=models.FloatField(default=0, verbose_name='Trigo Art. 12'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat12_ros',
            field=models.FloatField(default=0, verbose_name='Trigo Art. 12'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat_bas',
            field=models.FloatField(default=0, verbose_name='Trigo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat_bb',
            field=models.FloatField(default=0, verbose_name='Trigo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat_qq',
            field=models.FloatField(default=0, verbose_name='Trigo'),
        ),
        migrations.AlterField(
            model_name='board',
            name='wheat_ros',
            field=models.FloatField(default=0, verbose_name='Trigo'),
        ),
    ]
