# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-16 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20170213_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_point', models.IntegerField(verbose_name='Punto de Ingreso')),
                ('analysis_number', models.IntegerField(verbose_name='Numero de Analisis')),
                ('analysis', models.CharField(max_length=13, verbose_name='Analisis')),
                ('date', models.DateField(verbose_name='Fecha de Analisis')),
                ('newsletter_number', models.CharField(max_length=20, verbose_name='Numero de Boletin')),
                ('field', models.IntegerField(verbose_name='Campo')),
                ('lot', models.CharField(max_length=10, verbose_name='Lote')),
                ('field_description', models.CharField(max_length=100, verbose_name='Nombre de Campo')),
                ('species', models.CharField(max_length=4, verbose_name='Especie')),
                ('harvest', models.CharField(max_length=4, verbose_name='Cosecha')),
                ('protein', models.FloatField(verbose_name='Contenido Proteico')),
                ('grade', models.IntegerField(verbose_name='Grado')),
                ('factor', models.FloatField(verbose_name='Factor')),
                ('analysis_costs', models.FloatField(verbose_name='Gastos de Analisis')),
                ('gluten', models.IntegerField(verbose_name='Gluten')),
                ('analysis_item', models.IntegerField(verbose_name='Rubro de Analisis')),
                ('percentage', models.FloatField(verbose_name='Porcentaje')),
                ('bonus', models.FloatField(verbose_name='Bonificacion')),
                ('reduction', models.FloatField(verbose_name='Rebaja')),
                ('item_descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Analisis',
            },
        ),
        migrations.CreateModel(
            name='Remittances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_point', models.IntegerField(verbose_name='Punto de Ingreso')),
                ('analysis_number', models.IntegerField(verbose_name='Numero de Analisis')),
                ('analysis', models.CharField(max_length=13, verbose_name='Analisis')),
                ('date', models.DateField(verbose_name='Fecha de Analisis')),
                ('entry_point_ticket', models.IntegerField(verbose_name='Punto de Ingreso Ticket')),
                ('ticket_number', models.IntegerField(verbose_name='Numero de Ticket')),
                ('certified', models.BooleanField(default=True, verbose_name='Certificado')),
                ('ticket', models.CharField(max_length=16, verbose_name='Ticket')),
                ('ticket_date', models.DateField(verbose_name='Fecha de Ticket')),
                ('net_kg', models.IntegerField(verbose_name='Kilos Netos')),
            ],
            options={
                'verbose_name': 'Remesa',
                'verbose_name_plural': 'Remesas',
            },
        ),
    ]
