# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 20:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20170219_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2017, 2, 22, 20, 39, 10, 701000, tzinfo=utc), verbose_name='Vigencia Desde'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2017, 2, 22, 20, 39, 20, 233000, tzinfo=utc), verbose_name='Vigencia Hasta'),
            preserve_default=False,
        ),
    ]
