# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-24 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20170222_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='algoritmo_code',
            field=models.IntegerField(unique=True, verbose_name='Cuenta Algoritmo'),
        ),
    ]
