# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-27 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_remove_userinfo_old_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='account_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
