# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_userinfo_random_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('state', models.CharField(choices=[('BUE', 'Buenos Aires'), ('CHA', 'Chaco')], default='BUE', max_length=3, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
            },
        ),
        migrations.CreateModel(
            name='Rain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Lluvia',
                'verbose_name_plural': 'Lluvias',
            },
        ),
        migrations.CreateModel(
            name='RainDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mm', models.FloatField(verbose_name='Milimetros')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.City')),
                ('rain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rain')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
            },
        ),
    ]
