# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-02 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_city_rain_raindetail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raindetail',
            unique_together=set([('rain', 'city')]),
        ),
    ]
