# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-03 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_auto_20170302_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raindetail',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.City', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='raindetail',
            name='rain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rain', verbose_name='Fecha'),
        ),
    ]
