# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_accesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='algoritmo_code',
            field=models.IntegerField(default=1, verbose_name='Cuenta Algoritmo'),
            preserve_default=False,
        ),
    ]
