# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-05-05 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_auto_20170422_1559'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
        migrations.DeleteModel(
            name='Remittances',
        ),
    ]
