# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-06-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_userinfo_is_commercial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctacte',
            name='date_1',
            field=models.DateField(null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='ctacte',
            name='date_2',
            field=models.DateField(null=True, verbose_name='Fecha Emisi\xf3n'),
        ),
    ]
