# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-10 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20180209_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesHarvest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algoritmo_code', models.IntegerField(verbose_name='Cuenta Algoritmo')),
                ('movement_type', models.CharField(max_length=1, verbose_name='Tipo Movimiento')),
                ('species', models.CharField(max_length=4, verbose_name='Especie')),
                ('harvest', models.CharField(max_length=4, verbose_name='Cosecha')),
                ('speciesharvest', models.CharField(max_length=8, null=True, verbose_name='Especie Cosecha')),
                ('species_description', models.CharField(max_length=50, verbose_name='Especie y Cosecha')),
            ],
            options={
                'verbose_name': 'Especies y Cosechas',
            },
        ),
    ]
