# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-02-20 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0041_speciesharvest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsanalysis',
            name='speciesharvest',
            field=models.CharField(max_length=8, null=True, verbose_name='Especie Cosecha'),
        ),
    ]
